version: '3.7'

services:
  consul-server-01:
    image: consul:1.11.2
    container_name: consul-server-01
    hostname: consul-server-01
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./servers/consul-server-01:/etc/consul.d
    networks:
      - fullcycle-network

  consul-server-02:
    image: consul:1.11.2
    container_name: consul-server-02
    hostname: consul-server-02
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./servers/consul-server-02:/etc/consul.d
    networks:
      - fullcycle-network

  consul-server-03:
    image: consul:1.11.2
    container_name: consul-server-03
    hostname: consul-server-03
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./servers/consul-server-03:/etc/consul.d
    networks:
      - fullcycle-network

  consul-client-01:
    image: consul:1.11.2
    container_name: consul-client-01
    hostname: consul-client-01
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./clients/consul-client-01:/etc/consul.d
    networks:
      - fullcycle-network

  consul-client-02:
    image: consul:1.11.2
    container_name: consul-client-02
    hostname: consul-client-02
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./clients/consul-client-02:/etc/consul.d
    networks:
      - fullcycle-network

networks:
  fullcycle-network:
    driver: bridge
